// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ListModalController from "./list_modal_controller"
application.register("list-modal", ListModalController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SearchMoviesController from "./search_movies_controller"
application.register("search-movies", SearchMoviesController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
